import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthListener from "@/components/AuthListener";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import NotificationProvider from "@/components/notifications/NotificationProvider";
import { getCurrentUser } from "@/services";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-Powered Recruitment",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthListener />
        {user && <NotificationProvider userId={user.id} />}
        <Header />
        {children}
        <Footer />

        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              textAlign: "left",
            },
          }}
        />
      </body>
    </html>
  );
}
